version: "3.3"

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

services:

  db:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=avt_db
    ports:
      - "5432:5432"
    networks:
      network:
        ipv4_address: 172.25.0.2
    restart: always

  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3030:3030"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    networks:
      network:
        ipv4_address: 172.25.0.3
    restart: on-failure