import { ApiProperty } from '@nestjs/swagger';

export class ValidateRecoverCodeDTO {
  @ApiProperty({
    example: 'snvoe',
  })
  recoverCode: string;
}

export class ValidatedUserWithCodeDTO {
  @ApiProperty({
    example:
      'ileruhsbnflkgjshdfklgjhsdklfjhgpqoweiuqnfsjdfhlshlkjhsdflkghjklsdfg',
    description: `Token generated by the api`,
  })
  access_token: string;
}
